// Auto-generated by @components-kit/cli
// Do not edit manually

declare module "@components-kit/react" {
  interface ComponentsKitVariants {
    alert: "default" | "destructive" | "success" | "warning";
    badge: "default" | "destructive" | "outline" | "secondary" | "success" | "warning";
    button: "destructive" | "ghost" | "icon" | "link" | "outline" | "primary" | "secondary";
    checkbox: "default";
    combobox: "default";
    heading: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
    icon: "default";
    input: "default";
    multi_select: "default";
    pagination: "default";
    progress: "default";
    radio_group: "default";
    select: "default";
    separator: "default";
    skeleton: "default";
    slider: "default";
    switch: "default";
    table: "default";
    tabs: "default";
    text: "body1" | "body2" | "body3";
    textarea: "default";
    toast: "default" | "destructive" | "success" | "warning";
  }
}

export {};
