import type { ComponentVariant } from "./fetch-variants";

/**
 * Generate TypeScript module augmentation for @components-kit/react.
 * Fills in the ComponentsKitVariants register interface so that
 * each component's `variantName` prop gets autocomplete.
 */
export function generateTypeScript(
  components: Record<string, ComponentVariant>,
): string {
  const lines: string[] = [];

  lines.push("// Auto-generated by @components-kit/cli");
  lines.push("// Do not edit manually");
  lines.push("");
  lines.push('declare module "@components-kit/react" {');
  lines.push("  interface ComponentsKitVariants {");

  const sortedNames = Object.keys(components).sort();
  for (const name of sortedNames) {
    const { variants } = components[name];
    const union =
      variants.length > 0 ? variants.map((v) => `"${v}"`).join(" | ") : "never";
    lines.push(`    ${name}: ${union};`);
  }

  lines.push("  }");
  lines.push("}");
  lines.push("");
  lines.push("export {};");
  lines.push("");

  return lines.join("\n");
}
