/**
 * Register interface for component variant types.
 *
 * This interface is empty by default — all `variantName` props accept `string`.
 * Run `ck generate` from @components-kit/cli to augment this interface with
 * your project's actual variant names, enabling autocomplete.
 *
 * @example
 * // Generated by @components-kit/cli in types/components-kit.d.ts:
 * declare module "@components-kit/react" {
 *   interface ComponentsKitVariants {
 *     button: "primary" | "secondary" | "outline";
 *   }
 * }
 */

export interface ComponentsKitVariants {}

/**
 * Look up variant names for a component.
 * Resolves to the registered union if augmented, otherwise falls back to `string`.
 */
export type VariantFor<T extends string> =
  T extends keyof ComponentsKitVariants
    ? ComponentsKitVariants[T]
    : string;
