/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as EsmDemoRouteImport } from "./routes/esm-demo";
import { Route as IndexRouteImport } from "./routes/index";

const EsmDemoRoute = EsmDemoRouteImport.update({
  id: "/esm-demo",
  path: "/esm-demo",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/esm-demo": typeof EsmDemoRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/esm-demo": typeof EsmDemoRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/esm-demo": typeof EsmDemoRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/esm-demo";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/esm-demo";
  id: "__root__" | "/" | "/esm-demo";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  EsmDemoRoute: typeof EsmDemoRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/esm-demo": {
      id: "/esm-demo";
      path: "/esm-demo";
      fullPath: "/esm-demo";
      preLoaderRoute: typeof EsmDemoRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EsmDemoRoute: EsmDemoRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
