import { codeToHtml } from "shiki";

import { EditorPanel } from "./editor-panel";
import { GradientVisual } from "./gradient-visual";

const terminalSnippet = `$ ck generate

Fetching component variants from https://api.componentskit.com...
Found 21 components with 45 variants
Generated types/components-kit.d.ts`;

const typesSnippet = `// Auto-generated by @components-kit/cli
// Do not edit manually

declare module "@components-kit/react" {
  interface ComponentsKitVariants {
    alert: "default" | "destructive" | "success" | "warning";
    badge: "default" | "destructive" | "outline" | "secondary";
    button: "destructive" | "ghost" | "outline" | "primary";
    checkbox: "default";
    select: "default";
    switch: "default";
    text: "body1" | "body2" | "body3";
  }
}`;

const terminalLineCount = terminalSnippet.split("\n").length;
const typesLineCount = typesSnippet.split("\n").length;

export async function TypeGenVisual() {
  let terminalHtml: string;
  let typesHtml: string;

  try {
    [terminalHtml, typesHtml] = await Promise.all([
      codeToHtml(terminalSnippet, {
        defaultColor: false,
        lang: "text",
        themes: { dark: "github-dark-dimmed", light: "github-light" },
      }),
      codeToHtml(typesSnippet, {
        defaultColor: false,
        lang: "typescript",
        themes: { dark: "github-dark-dimmed", light: "github-light" },
      }),
    ]);
  } catch {
    return <pre className="p-4 text-xs font-mono text-neutral-500">{typesSnippet}</pre>;
  }

  return (
    <div className="relative h-64 sm:h-96 rounded-xl overflow-hidden will-change-transform">
      <GradientVisual
        className="absolute inset-0"
        darkGlows={[
          { blur: "blur-3xl", color: "oklch(46% 0.105 255 / 0.34)", position: "-top-16 -right-16", size: "h-52 w-52" },
          { blur: "blur-3xl", color: "oklch(44% 0.09 245 / 0.3)", position: "bottom-1/3 -left-12", size: "h-48 w-48" },
          { blur: "blur-2xl", color: "oklch(47% 0.085 265 / 0.24)", position: "-bottom-16 right-1/3", size: "h-56 w-56" },
        ]}
        darkGradient="linear-gradient(200deg, oklch(22% 0.018 255) 0%, oklch(18% 0.018 245) 52%, oklch(15.5% 0.016 265) 100%)"
        glows={[
          { blur: "blur-3xl", color: "oklch(82% 0.13 255 / 0.44)", position: "-top-16 -right-16", size: "h-52 w-52" },
          { blur: "blur-3xl", color: "oklch(84% 0.105 245 / 0.32)", position: "bottom-1/3 -left-12", size: "h-48 w-48" },
          { blur: "blur-2xl", color: "oklch(81% 0.105 265 / 0.26)", position: "-bottom-16 right-1/3", size: "h-56 w-56" },
        ]}
        gradient="linear-gradient(200deg, oklch(95.5% 0.026 255) 0%, oklch(92% 0.034 245) 52%, oklch(89.5% 0.032 265) 100%)"
      />

      {/* Back editor — Terminal output */}
      <EditorPanel
        className="absolute top-6 left-6 sm:top-10 sm:left-10 -right-8 -bottom-8 sm:-right-12 sm:-bottom-12 flex flex-col rounded-tl-lg overflow-hidden border border-neutral-200 shadow-xl"
        style={{ backgroundColor: "oklch(98% 0 0)" }}
        darkStyle={{ backgroundColor: "#1e1e1e" }}
        filename="terminal"
        html={terminalHtml}
        lineCount={terminalLineCount}
      />

      {/* Front editor — Generated types */}
      <EditorPanel
        className="absolute top-32 left-20 sm:top-48 sm:left-36 -right-4 -bottom-8 sm:-right-6 sm:-bottom-12 flex flex-col rounded-tl-lg overflow-hidden border border-neutral-200 shadow-2xl"
        style={{ backgroundColor: "oklch(98% 0 0)" }}
        darkStyle={{ backgroundColor: "#1e1e1e" }}
        filename="components-kit.d.ts"
        html={typesHtml}
        lineCount={typesLineCount}
      />
    </div>
  );
}
