import {
  alertDemo,
  asyncSelectDemo,
  badgeDemo,
  buttonDemo,
  checkboxDemo,
  comboboxDemo,
  headingDemo,
  iconDemo,
  inputDemo,
  multiSelectDemo,
  paginationDemo,
  progressDemo,
  radioGroupDemo,
  selectDemo,
  separatorDemo,
  skeletonDemo,
  sliderDemo,
  switchDemo,
  tableDemo,
  tabsDemo,
  textareaDemo,
  textDemo,
  toastDemo,
} from "./demos";
import { type ComponentDemo } from "./types";

export const componentDemos: ComponentDemo[] = [
  alertDemo,
  asyncSelectDemo,
  badgeDemo,
  buttonDemo,
  checkboxDemo,
  comboboxDemo,
  headingDemo,
  iconDemo,
  inputDemo,
  multiSelectDemo,
  paginationDemo,
  progressDemo,
  radioGroupDemo,
  selectDemo,
  separatorDemo,
  skeletonDemo,
  sliderDemo,
  switchDemo,
  tableDemo,
  tabsDemo,
  textDemo,
  textareaDemo,
  toastDemo,
];
